name: daredis
description: A Redis client for Dart with connection pooling, cluster support, dedicated Pub/Sub and transaction sessions, and typed helper APIs.
version: 0.0.1
repository: https://github.com/vacivor/daredis
homepage: https://github.com/vacivor/daredis
issue_tracker: https://github.com/vacivor/daredis/issues

environment:
  sdk: ^3.10.7

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
